#!/usr/bin/env python3
"""
load_logging_xml.py — load enwiki-<run>-pages-logging.xml.gz into wiki20260401.

Phase 1b of the data-collection plan. WMF stopped publishing `logging.sql.gz`,
so the equivalent content arrives as MediaWiki <logitem> elements inside the
recombined `pages-logging.xml.gz` (or its 27 splits). This script streams that
XML, normalizes `log_params` to JSON, synthesizes a row in `actor` for each
contributor it has not seen yet, and bulk-loads `logging` via psycopg COPY.

Connects via libpq service=wiki (port encoded in ~/.pg_service.conf).

Co-design with the revision loader: the `actor` table is shared. Both loaders
must deduplicate the same way and never TRUNCATE it. The actor table itself
holds a UNIQUE NULLS NOT DISTINCT constraint on (actor_user, actor_name) and
its actor_id is a GENERATED BY DEFAULT AS IDENTITY column, so we never
allocate ids ourselves. For each unseen contributor we run
``INSERT ... ON CONFLICT (actor_user, actor_name) DO NOTHING RETURNING
actor_id``; if a concurrent/prior loader already inserted the row we
SELECT the id back. A bounded in-process LRU caches resolved ids so steady
state is one extra round-trip only on cache miss.

Examples:
  python load_logging_xml.py
  python load_logging_xml.py --file <path-to.xml.gz>
  python load_logging_xml.py --file <path> --limit 50000
  python load_logging_xml.py --dry-run
  python load_logging_xml.py --keep-indexes
  python load_logging_xml.py --self-test           # in-script unit tests, no DB
"""

from __future__ import annotations

import argparse
import collections
import datetime as dt
import gzip
import io
import json
import logging
import re
import sys
import time
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator, Optional

import phpserialize
import psycopg

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_FILE = Path(
    "/media/simone/ssd1/wikidumps/20260401/xml/enwiki-20260401-pages-logging.xml.gz"
)
SERVICE = "wiki"
BATCH_SIZE = 5000
PROGRESS_EVERY = 100_000

# Tables touched by this loader.
LOGGING_TABLE = "logging"
ACTOR_TABLE = "actor"

# Indexes to drop/recreate on logging. Discovered from schema/indexes.sql at
# runtime, but we record the names here so we know which ones to look for.
LOGGING_INDEX_NAMES = (
    "logging_type_timestamp_idx",
    "logging_namespace_title_idx",
    "logging_page_idx",
    "logging_actor_idx",
    "logging_params_gin_idx",
)
INDEXES_SQL_PATH = (
    Path(__file__).resolve().parent / "schema" / "indexes.sql"
)

# Per-session performance tuning (loader opens its own connection).
SESSION_TUNING_SQL = (
    "SET LOCAL synchronous_commit = OFF",
    "SET LOCAL maintenance_work_mem = '2GB'",
)

log = logging.getLogger("load_logging_xml")


# ---------------------------------------------------------------------------
# log_params parsing
# ---------------------------------------------------------------------------

def _to_jsonable(obj: Any) -> Any:
    """Recursively coerce a phpserialize-decoded structure to JSON-safe types.

    phpserialize yields:
      * dicts keyed by either ints or bytes
      * lists of values
      * bytes (PHP strings)
      * ints / floats / bool / None

    Postgres jsonb requires:
      * dicts with str keys
      * everything else JSON-serializable
    """
    if isinstance(obj, dict):
        out: dict[str, Any] = {}
        for k, v in obj.items():
            if isinstance(k, bytes):
                # PHP strings: best-effort UTF-8, fall back to latin-1 to never raise.
                try:
                    sk = k.decode("utf-8")
                except UnicodeDecodeError:
                    sk = k.decode("latin-1")
            else:
                sk = str(k)
            out[sk] = _to_jsonable(v)
        return out
    if isinstance(obj, (list, tuple)):
        return [_to_jsonable(x) for x in obj]
    if isinstance(obj, bytes):
        try:
            return obj.decode("utf-8")
        except UnicodeDecodeError:
            return obj.decode("latin-1")
    # int, float, bool, None, str — already jsonable.
    return obj


def parse_log_params(raw: Optional[str]) -> Optional[Any]:
    """Parse the MediaWiki log_params blob.

    Returns a JSON-serializable Python value, or None if `raw` is None/empty.

    Strategy: try JSON first (newer rows), then phpserialize (older rows),
    finally fall back to {"raw": raw} for the rare freeform/key=value style.
    """
    if raw is None:
        return None
    s = raw.strip()
    if not s:
        return None

    # 1. JSON — by far the most common in 2020+ rows.
    try:
        return json.loads(s)
    except (json.JSONDecodeError, ValueError):
        pass

    # 2. PHP-serialized — common in pre-2018 rows.
    # phpserialize raises a few different exception types depending on the
    # malformation. Catch broadly; the freeform fallback below is a safe net.
    try:
        decoded = phpserialize.loads(s.encode("utf-8", errors="surrogateescape"))
        return _to_jsonable(decoded)
    except Exception:
        pass

    # 3. Freeform — preserve the original string for later inspection.
    return {"raw": raw}


# ---------------------------------------------------------------------------
# XML streaming
# ---------------------------------------------------------------------------
#
# We initially used `mwxml.Dump` for parsing, but on real enwiki data its
# User.from_element raises TypeError on `<contributor><id /></contributor>`
# (empty <id> element, which appears in the wild). Rather than monkey-patch
# mwxml, we roll a small iterparse-based parser. The schema is fixed and tiny
# (id, timestamp, contributor{username,id,ip}, comment, type, action,
# logtitle, params), so this stays small.

# MediaWiki export-0.11 namespace.
_MW_NS = "{http://www.mediawiki.org/xml/export-0.11/}"


@dataclass
class ParsedLogItem:
    id: Optional[int]
    type: Optional[str]
    action: Optional[str]
    timestamp: Optional[str]
    comment: Optional[str]
    comment_deleted: bool
    user_text: Optional[str]
    user_id: Optional[int]
    user_deleted: bool
    logtitle: Optional[str]
    params: Optional[str]


def open_xml_stream(path: Path) -> io.IOBase:
    """Return a binary file-like that ElementTree's iterparse can read."""
    if path.suffix == ".gz":
        return gzip.open(str(path), "rb")
    return open(path, "rb")


def _localname(tag: str) -> str:
    """Strip the {namespace} prefix from an ElementTree tag."""
    if tag.startswith("{"):
        return tag.rsplit("}", 1)[1]
    return tag


def _parse_namespaces(siteinfo_elem: ET.Element) -> dict[str, int]:
    """Build {prefix-lowercase: int_key} from <siteinfo>/<namespaces>.

    Used to split a logtitle like "User talk:Foo" into (3, "Foo"). We only
    look up by canonical/localized prefix; if the title doesn't match any
    known prefix we treat it as namespace 0 (Main).
    """
    ns_map: dict[str, int] = {}
    namespaces = siteinfo_elem.find(f"{_MW_NS}namespaces")
    if namespaces is None:
        return ns_map
    for n in namespaces.findall(f"{_MW_NS}namespace"):
        key = n.get("key")
        if key is None:
            continue
        try:
            key_int = int(key)
        except ValueError:
            continue
        prefix = (n.text or "").strip()
        if prefix:
            ns_map[prefix.lower()] = key_int
    return ns_map


def split_title(logtitle: str, ns_map: dict[str, int]) -> tuple[int, str]:
    """Decompose 'User talk:Foo' → (3, 'Foo'). Default to (0, full)."""
    if ":" in logtitle:
        prefix, _, rest = logtitle.partition(":")
        ns_id = ns_map.get(prefix.lower())
        if ns_id is not None:
            return ns_id, rest
    return 0, logtitle


def _text_or_none(elem: Optional[ET.Element]) -> Optional[str]:
    if elem is None:
        return None
    return elem.text  # may itself be None for <tag />


def _parse_contributor(c: ET.Element) -> tuple[
    Optional[str], Optional[int], bool
]:
    """Return (user_text, user_id, deleted)."""
    if c.get("deleted") is not None:
        return None, None, True
    username_e = c.find(f"{_MW_NS}username")
    ip_e = c.find(f"{_MW_NS}ip")
    id_e = c.find(f"{_MW_NS}id")
    user_text: Optional[str] = None
    user_id: Optional[int] = None
    if username_e is not None and username_e.text:
        user_text = username_e.text
    elif ip_e is not None and ip_e.text:
        user_text = ip_e.text
    if id_e is not None and id_e.text and id_e.text.strip():
        try:
            user_id = int(id_e.text)
        except ValueError:
            user_id = None
    return user_text, user_id, False


def iter_logitems(path: Path) -> Iterator[tuple[ParsedLogItem, dict[str, int]]]:
    """Yield (ParsedLogItem, ns_map) tuples.

    ns_map is built from <siteinfo> and reused across all items in the file.
    Yielded as a tuple so callers don't have to thread the namespace map
    out-of-band.
    """
    f = open_xml_stream(path)
    ns_map: dict[str, int] = {}
    try:
        # iterparse with 'end' events so each child is fully populated.
        context = ET.iterparse(f, events=("end",))
        for event, elem in context:
            tag = _localname(elem.tag)
            if tag == "siteinfo":
                ns_map = _parse_namespaces(elem)
                elem.clear()
                continue
            if tag != "logitem":
                # Don't clear <namespaces>/<namespace> here — they're inside
                # siteinfo and will be cleared by elem.clear() above.
                continue

            # Parse this <logitem>.
            id_e = elem.find(f"{_MW_NS}id")
            ts_e = elem.find(f"{_MW_NS}timestamp")
            type_e = elem.find(f"{_MW_NS}type")
            action_e = elem.find(f"{_MW_NS}action")
            logtitle_e = elem.find(f"{_MW_NS}logtitle")
            params_e = elem.find(f"{_MW_NS}params")
            comment_e = elem.find(f"{_MW_NS}comment")
            contributor_e = elem.find(f"{_MW_NS}contributor")

            log_id: Optional[int] = None
            if id_e is not None and id_e.text and id_e.text.strip():
                try:
                    log_id = int(id_e.text)
                except ValueError:
                    log_id = None

            comment_deleted = False
            comment_text: Optional[str] = None
            if comment_e is not None:
                if comment_e.get("deleted") is not None:
                    comment_deleted = True
                else:
                    comment_text = comment_e.text

            user_text: Optional[str] = None
            user_id: Optional[int] = None
            user_deleted = False
            if contributor_e is not None:
                user_text, user_id, user_deleted = _parse_contributor(
                    contributor_e
                )

            item = ParsedLogItem(
                id=log_id,
                type=_text_or_none(type_e),
                action=_text_or_none(action_e),
                timestamp=_text_or_none(ts_e),
                comment=comment_text,
                comment_deleted=comment_deleted,
                user_text=user_text,
                user_id=user_id,
                user_deleted=user_deleted,
                logtitle=_text_or_none(logtitle_e),
                params=_text_or_none(params_e),
            )
            yield item, ns_map
            # Free memory: drop this logitem's subtree.
            elem.clear()
    finally:
        try:
            f.close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Actor synthesis
# ---------------------------------------------------------------------------

ACTOR_CACHE_MAX = 1_000_000


class ActorRegistry:
    """DB-backed actor resolver with a bounded LRU.

    Key:    (actor_user_or_None, actor_name_bytes)
    Value:  actor_id (bigint allocated by the DB IDENTITY column)

    The schema declares ``actor_id GENERATED BY DEFAULT AS IDENTITY`` and
    ``UNIQUE NULLS NOT DISTINCT (actor_user, actor_name)``. We rely on both:
    INSERT ... ON CONFLICT DO NOTHING RETURNING actor_id either mints a fresh
    id or returns no row (because the constraint already holds a row); on
    conflict we SELECT the existing id back. The two loaders converge on the
    same actor_id for the same (actor_user, actor_name) regardless of order.

    The LRU is just a memory-bound cache to skip the round-trip when we see
    the same contributor again in this process. Cap defaults to 1M entries.
    """

    def __init__(self, conn: psycopg.Connection, max_size: int = ACTOR_CACHE_MAX):
        self._conn = conn
        self._max_size = max_size
        # OrderedDict for cheap LRU semantics.
        from collections import OrderedDict
        self._cache: "OrderedDict[tuple[Optional[int], bytes], int]" = OrderedDict()
        self._sel_sql = (
            f"SELECT actor_id FROM {ACTOR_TABLE} "
            "WHERE actor_user IS NOT DISTINCT FROM %s AND actor_name = %s"
        )
        self._ins_sql = (
            f"INSERT INTO {ACTOR_TABLE} (actor_user, actor_name) VALUES (%s, %s) "
            "ON CONFLICT (actor_user, actor_name) DO NOTHING "
            "RETURNING actor_id"
        )

    def get_or_create(
        self, actor_user: Optional[int], actor_name: bytes
    ) -> int:
        key = (actor_user, actor_name)
        cached = self._cache.get(key)
        if cached is not None:
            self._cache.move_to_end(key)
            return cached
        with self._conn.cursor() as cur:
            cur.execute(self._ins_sql, (actor_user, actor_name))
            row = cur.fetchone()
            if row is not None:
                actor_id = row[0]
            else:
                # Conflict: row already exists. SELECT it back.
                cur.execute(self._sel_sql, (actor_user, actor_name))
                got = cur.fetchone()
                if got is None:
                    # Should not happen given the unique constraint, but
                    # guard against a transient anomaly.
                    raise RuntimeError(
                        f"actor row vanished after ON CONFLICT for "
                        f"(actor_user={actor_user!r}, actor_name={actor_name!r})"
                    )
                actor_id = got[0]
        self._cache[key] = actor_id
        self._cache.move_to_end(key)
        if len(self._cache) > self._max_size:
            self._cache.popitem(last=False)
        return actor_id


# ---------------------------------------------------------------------------
# Index drop / recreate
# ---------------------------------------------------------------------------

def parse_logging_index_statements(indexes_sql: Path) -> dict[str, str]:
    """Parse schema/indexes.sql and return {index_name: full CREATE statement}
    for each logging-table index we know about."""
    text = indexes_sql.read_text(encoding="utf-8")
    statements: dict[str, str] = {}
    # Split on ';' at end of lines — each CREATE INDEX is one statement.
    # Handle multi-line statements (everything up to the next ';').
    raw_stmts = [s.strip() for s in text.split(";") if s.strip()]
    for stmt in raw_stmts:
        # Strip leading psql meta lines (\set, comments) defensively.
        # Match "CREATE INDEX [IF NOT EXISTS] name".
        m = re.search(
            r"CREATE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z0-9_]+)",
            stmt, flags=re.IGNORECASE,
        )
        if not m:
            continue
        name = m.group(1)
        if name in LOGGING_INDEX_NAMES:
            # Strip leading SQL comments so each statement re-runs cleanly.
            cleaned = re.sub(r"^\s*--[^\n]*\n", "", stmt, flags=re.MULTILINE)
            statements[name] = cleaned.strip() + ";"
    return statements


def drop_logging_indexes(conn: psycopg.Connection) -> dict[str, str]:
    """DROP every known logging index. Returns the saved CREATE statements.

    Idempotent: missing indexes are fine (DROP IF EXISTS).
    """
    creates = parse_logging_index_statements(INDEXES_SQL_PATH)
    missing = [n for n in LOGGING_INDEX_NAMES if n not in creates]
    if missing:
        log.warning(
            "indexes.sql parsed but these expected indexes were not found: %s",
            missing,
        )
    with conn.cursor() as cur:
        for name in LOGGING_INDEX_NAMES:
            log.info("dropping index %s", name)
            cur.execute(f"DROP INDEX IF EXISTS {name}")
    conn.commit()
    return creates


def recreate_logging_indexes(
    conn: psycopg.Connection, creates: dict[str, str]
) -> None:
    """Recreate the indexes we dropped, in the original order."""
    with conn.cursor() as cur:
        for name in LOGGING_INDEX_NAMES:
            stmt = creates.get(name)
            if not stmt:
                log.warning("no recreate statement for %s; skipping", name)
                continue
            log.info("recreating index %s", name)
            t0 = time.time()
            cur.execute(stmt)
            log.info("  -> %s built in %.1fs", name, time.time() - t0)
    conn.commit()


# ---------------------------------------------------------------------------
# Logging-table COPY
# ---------------------------------------------------------------------------

LOGGING_COLS = (
    "log_id",
    "log_type",
    "log_action",
    "log_timestamp",
    "log_actor",
    "log_actor_name",
    "log_namespace",
    "log_title",
    "log_page",
    "log_comment",
    "log_params",
    "log_deleted",
)

def _parse_ts(s: str) -> Optional[dt.datetime]:
    """Parse a MediaWiki ISO-8601 UTC timestamp ('2020-01-01T00:00:00Z')."""
    if not s:
        return None
    # Python's fromisoformat doesn't accept the trailing 'Z' until 3.11.
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        return dt.datetime.fromisoformat(s)
    except ValueError:
        return None


def _logitem_to_row(
    item: ParsedLogItem,
    ns_map: dict[str, int],
    actors: ActorRegistry,
) -> Optional[tuple]:
    """Map a ParsedLogItem to a row tuple matching LOGGING_COLS.

    Returns None if the item is unusable (no id, no type, no timestamp).
    """
    if item.id is None or item.type is None or item.timestamp is None:
        return None
    ts = _parse_ts(item.timestamp)
    if ts is None:
        return None

    # type/action are NOT NULL in our schema. action defaults to type if missing
    # (some old rows have no <action>).
    log_type = item.type
    log_action = item.action or item.type

    # logtitle: decompose with the dump's namespace map.
    if item.logtitle:
        log_namespace, title_str = split_title(item.logtitle, ns_map)
    else:
        log_namespace, title_str = 0, ""
    log_title_bytes = title_str.encode("utf-8", errors="surrogateescape")

    # contributor → actor synthesis.
    actor_id: Optional[int]
    actor_name_bytes: Optional[bytes]
    if item.user_deleted or item.user_text is None:
        actor_id = None
        actor_name_bytes = None
    else:
        actor_name_bytes = item.user_text.encode(
            "utf-8", errors="surrogateescape"
        )
        actor_id = actors.get_or_create(item.user_id, actor_name_bytes)

    log_comment = None if item.comment_deleted else item.comment

    # log_deleted: mirror MW's bitmask. The XML only flags comment/user for
    # log items (no text-suppression flag), so we set bits 2 and 4 only.
    log_deleted = 0
    if item.comment_deleted:
        log_deleted |= 2
    if item.user_deleted:
        log_deleted |= 4

    log_params = parse_log_params(item.params)
    log_params_json = (
        json.dumps(log_params, ensure_ascii=False)
        if log_params is not None else None
    )

    return (
        int(item.id),
        log_type,
        log_action,
        ts,
        actor_id,
        actor_name_bytes,
        int(log_namespace),
        log_title_bytes,
        None,  # log_page — not in pages-logging.xml
        log_comment,
        log_params_json,
        log_deleted,
    )


def _copy_logging_batch(
    conn: psycopg.Connection, rows: list[tuple]
) -> None:
    """Bulk-load a batch of logging rows via text-format COPY.

    We use the text format (not binary) because jsonb in binary COPY needs
    a hand-built leading version byte; text format lets psycopg/Postgres
    handle the encoding for every column type uniformly.
    """
    if not rows:
        return
    with conn.cursor() as cur:
        with cur.copy(
            f"COPY {LOGGING_TABLE} ({', '.join(LOGGING_COLS)}) FROM STDIN"
        ) as cp:
            for r in rows:
                cp.write_row(r)


# ---------------------------------------------------------------------------
# Main load
# ---------------------------------------------------------------------------

def load(
    file_path: Path,
    *,
    limit: Optional[int] = None,
    dry_run: bool = False,
    keep_indexes: bool = False,
) -> int:
    log.info("load: file=%s limit=%s dry_run=%s keep_indexes=%s",
             file_path, limit, dry_run, keep_indexes)
    if not file_path.exists():
        raise SystemExit(f"input file does not exist: {file_path}")

    type_hist: collections.Counter[str] = collections.Counter()
    seen = 0
    inserted = 0
    t0 = time.time()

    if dry_run:
        # Just iterate and count.
        for item, _ns_map in iter_logitems(file_path):
            seen += 1
            if item.type:
                type_hist[item.type] += 1
            if seen % PROGRESS_EVERY == 0:
                log.info("dry-run: parsed %d logitems in %.1fs",
                         seen, time.time() - t0)
            if limit and seen >= limit:
                break
        log.info("DRY-RUN summary: %d logitems parsed in %.1fs",
                 seen, time.time() - t0)
        log.info("type histogram: %s", type_hist.most_common(10))
        return seen

    # Real load. Open one connection; do everything in it.
    with psycopg.connect(f"service={SERVICE}") as conn:
        with conn.cursor() as cur:
            for stmt in SESSION_TUNING_SQL:
                cur.execute(stmt)

        actors = ActorRegistry(conn)

        saved_index_creates: dict[str, str] = {}
        if not keep_indexes:
            saved_index_creates = drop_logging_indexes(conn)

        # TRUNCATE logging only; never actor.
        with conn.cursor() as cur:
            log.info("TRUNCATE %s", LOGGING_TABLE)
            cur.execute(f"TRUNCATE TABLE {LOGGING_TABLE}")
        conn.commit()

        log_batch: list[tuple] = []

        try:
            for item, ns_map in iter_logitems(file_path):
                seen += 1
                if item.type:
                    type_hist[item.type] += 1
                row = _logitem_to_row(item, ns_map, actors)
                if row is None:
                    continue
                log_batch.append(row)

                if len(log_batch) >= BATCH_SIZE:
                    _copy_logging_batch(conn, log_batch)
                    inserted += len(log_batch)
                    log_batch.clear()
                    conn.commit()

                if seen % PROGRESS_EVERY == 0:
                    elapsed = time.time() - t0
                    rate = seen / elapsed if elapsed > 0 else 0.0
                    log.info(
                        "progress: %d parsed, %d inserted, %.0f rows/s, %.1fs",
                        seen, inserted, rate, elapsed,
                    )

                if limit and seen >= limit:
                    break

            # Flush remainder.
            _copy_logging_batch(conn, log_batch)
            inserted += len(log_batch)
            log_batch.clear()
            conn.commit()
        except Exception:
            log.exception("load failed; rolling back current batch")
            conn.rollback()
            raise

        if not keep_indexes and saved_index_creates:
            recreate_logging_indexes(conn, saved_index_creates)

        with conn.cursor() as cur:
            log.info("ANALYZE %s, %s", LOGGING_TABLE, ACTOR_TABLE)
            cur.execute(f"ANALYZE {LOGGING_TABLE}")
            cur.execute(f"ANALYZE {ACTOR_TABLE}")
        conn.commit()

    elapsed = time.time() - t0
    log.info("DONE in %.1fs", elapsed)
    log.info("seen=%d inserted=%d", seen, inserted)
    log.info("top log_types: %s", type_hist.most_common(10))
    return inserted


# ---------------------------------------------------------------------------
# Self-test (no DB)
# ---------------------------------------------------------------------------

def self_test() -> int:
    """Exercise log_params parsing and a few edge cases. Returns exit code."""
    failures: list[str] = []

    # 1. JSON form (newer rows: nested array).
    json_raw = '[["edit=sysop"],{"7d": 0, "1y": 0}]'
    out = parse_log_params(json_raw)
    expected = [["edit=sysop"], {"7d": 0, "1y": 0}]
    if out != expected:
        failures.append(f"JSON parse: got {out!r}, want {expected!r}")

    # 2. JSON dict form (block log).
    json_dict = '{"5::duration": "indefinite", "6::flags": "nocreate"}'
    out = parse_log_params(json_dict)
    if out != {"5::duration": "indefinite", "6::flags": "nocreate"}:
        failures.append(f"JSON-dict parse: got {out!r}")

    # 3. PHP-serialized array (older rows).
    # PHP equiv: a:1:{i:0;s:10:"edit=sysop";}
    # phpserialize represents this as {0: b'edit=sysop'} — int keys preserved
    # rather than being collapsed to a list. We stringify the keys for jsonb.
    php_raw = 'a:1:{i:0;s:10:"edit=sysop";}'
    out = parse_log_params(php_raw)
    if out != {"0": "edit=sysop"}:
        failures.append(f"PHP parse simple: got {out!r}")

    # 4. PHP-serialized assoc array with bytes keys.
    # a:2:{s:5:"level";s:5:"sysop";s:6:"expiry";s:8:"infinity";}
    php_assoc = 'a:2:{s:5:"level";s:5:"sysop";s:6:"expiry";s:8:"infinity";}'
    out = parse_log_params(php_assoc)
    if out != {"level": "sysop", "expiry": "infinity"}:
        failures.append(f"PHP parse assoc: got {out!r}")

    # 5. Freeform / unparseable: stored as {"raw": ...}.
    free_raw = "edit=sysop\nmove=sysop"
    out = parse_log_params(free_raw)
    if out != {"raw": free_raw}:
        failures.append(f"freeform fallback: got {out!r}")

    # 6. None / empty.
    if parse_log_params(None) is not None:
        failures.append("None did not return None")
    if parse_log_params("") is not None:
        failures.append("empty string did not return None")
    if parse_log_params("   ") is not None:
        failures.append("blank string did not return None")

    # 7. JSON-encodability of every result.
    for raw in (json_raw, json_dict, php_raw, php_assoc, free_raw):
        try:
            json.dumps(parse_log_params(raw), ensure_ascii=False)
        except (TypeError, ValueError) as e:
            failures.append(f"non-JSON-encodable for {raw!r}: {e}")

    # 8. ActorRegistry with a fake DB cursor that emulates the IDENTITY +
    # ON CONFLICT semantics. The real DB hands out monotonically-increasing
    # ids and dedups via the unique constraint; we mirror that in-memory.

    class _FakeIdentityCur:
        """Cursor stub: handles INSERT ... RETURNING and SELECT against an
        in-memory store. Shared across all cursors created from the same
        connection."""

        def __init__(self, store):
            self._store = store
            self._last_row: Optional[tuple] = None

        def __enter__(self):
            return self

        def __exit__(self, *a):
            return False

        def execute(self, sql: str, params=()):
            sql_lc = sql.lower()
            if sql_lc.startswith("insert into"):
                actor_user, actor_name = params
                key = (actor_user, actor_name)
                if key in self._store["map"]:
                    # Conflict: ON CONFLICT DO NOTHING returns no row.
                    self._last_row = None
                else:
                    new_id = self._store["next_id"]
                    self._store["next_id"] += 1
                    self._store["map"][key] = new_id
                    self._last_row = (new_id,)
            elif sql_lc.startswith("select actor_id"):
                actor_user, actor_name = params
                key = (actor_user, actor_name)
                aid = self._store["map"].get(key)
                self._last_row = (aid,) if aid is not None else None
            else:
                self._last_row = None

        def fetchone(self):
            return self._last_row

    class _FakeIdentityConn:
        def __init__(self):
            self._store = {"map": {}, "next_id": 1}

        def cursor(self):
            return _FakeIdentityCur(self._store)

    reg = ActorRegistry(_FakeIdentityConn())
    a = reg.get_or_create(123, b"Alice")
    b = reg.get_or_create(123, b"Alice")  # dedup
    c = reg.get_or_create(None, b"127.0.0.1")  # anonymous IP
    d = reg.get_or_create(None, b"127.0.0.1")
    if a != b:
        failures.append(f"actor dedup: a={a} b={b}")
    if c != d:
        failures.append(f"anon actor dedup: c={c} d={d}")
    if a == c:
        failures.append("distinct keys collapsed to same actor_id")

    # 9. _logitem_to_row edge: deleted contributor + missing comment.
    item = ParsedLogItem(
        id=7, type="delete", action="delete",
        timestamp="2020-01-01T00:00:00Z",
        comment=None, comment_deleted=True,
        user_text=None, user_id=None, user_deleted=True,
        logtitle="User talk:Foo", params=None,
    )
    ns_map = {"user talk": 3}
    row = _logitem_to_row(item, ns_map, reg)
    if row is None:
        failures.append("deleted item produced None row")
    else:
        # log_actor (col 4) must be NULL
        if row[4] is not None:
            failures.append(f"deleted contributor not NULL: {row[4]!r}")
        # log_namespace decomposed correctly
        if row[6] != 3:
            failures.append(f"namespace decomposition: got {row[6]}")
        if row[7] != b"Foo":
            failures.append(f"title bytes: got {row[7]!r}")
        # log_comment (col 9) must be NULL
        if row[9] is not None:
            failures.append(f"deleted comment not NULL: {row[9]!r}")
        # log_deleted (col 11) bitmask = 6 (comment=2 | user=4)
        if row[11] != 6:
            failures.append(f"log_deleted bitmask: got {row[11]}, want 6")

    # 10. _logitem_to_row: missing log_page case + present contributor.
    item2 = ParsedLogItem(
        id=8, type="protect", action="protect",
        timestamp="2020-01-01T00:00:00Z",
        comment="x", comment_deleted=False,
        user_text="Alice", user_id=42, user_deleted=False,
        logtitle="Donald Trump",
        params='[["edit=sysop"],{"7d":0}]',
    )
    row2 = _logitem_to_row(item2, {}, reg)
    if row2 is None:
        failures.append("normal protect item produced None row")
    elif row2[8] is not None:
        failures.append(f"log_page should be NULL: got {row2[8]!r}")
    elif row2[4] is None:
        failures.append("log_actor should be set for live contributor")

    if failures:
        print("SELF-TEST FAILURES:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print("self-test: all checks passed")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--file", type=Path, default=DEFAULT_FILE,
                   help=f"path to pages-logging XML[.gz] (default: {DEFAULT_FILE})")
    p.add_argument("--limit", type=int, default=None,
                   help="stop after N logitems (testing)")
    p.add_argument("--dry-run", action="store_true",
                   help="parse and count, but do not load")
    p.add_argument("--keep-indexes", action="store_true",
                   help="don't drop/recreate indexes around the load")
    p.add_argument("--self-test", action="store_true",
                   help="run in-script unit tests for log_params parsing and exit")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="enable DEBUG-level logging")
    args = p.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )

    if args.self_test:
        return self_test()

    load(
        args.file,
        limit=args.limit,
        dry_run=args.dry_run,
        keep_indexes=args.keep_indexes,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
