#!/usr/bin/env python3
"""
load_logging_xml.py — load enwiki-<run>-pages-logging.xml.gz into wiki20260401.

Phase 1b of the data-collection plan. WMF stopped publishing `logging.sql.gz`,
so the equivalent content arrives as MediaWiki <logitem> elements inside the
recombined `pages-logging.xml.gz` (or its 27 splits). This script streams that
XML, normalizes `log_params` to JSON, synthesizes a row in `actor` for each
contributor it has not seen yet, and bulk-loads `logging` via psycopg COPY.

Connects via libpq service=wiki (port encoded in ~/.pg_service.conf).

Co-design with the revision loader: the `actor` table is shared. Both loaders
must deduplicate the same way and never TRUNCATE it. The actor table itself
holds a UNIQUE NULLS NOT DISTINCT constraint on (actor_user, actor_name) and
its actor_id is a GENERATED BY DEFAULT AS IDENTITY column, so we never
allocate ids ourselves. Contributors are resolved a batch at a time: cache
misses are COPYed into a session TEMP table, minted with a single
``INSERT ... SELECT ... ON CONFLICT DO NOTHING``, then read back (minted or
pre-existing) with one join. A bounded in-process LRU absorbs the admins that
recur constantly, so most batches touch the DB only for genuinely new actors.

Examples:
  python load_logging_xml.py
  python load_logging_xml.py --file <path-to.xml.gz>
  python load_logging_xml.py --file <path> --limit 50000
  python load_logging_xml.py --dry-run
  python load_logging_xml.py --keep-indexes
  python load_logging_xml.py --self-test           # in-script unit tests, no DB
"""

from __future__ import annotations

import argparse
import collections
import datetime as dt
import gzip
import io
import json
import logging
import math
import re
import sys
import time
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator, Optional

import phpserialize
import psycopg

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_FILE = Path(
    "/media/simone/ssd1/wikidumps/20260401/xml/enwiki-20260401-pages-logging.xml.gz"
)
SERVICE = "wiki"
BATCH_SIZE = 10000
PROGRESS_EVERY = 100_000

# Tables touched by this loader.
LOGGING_TABLE = "logging"
ACTOR_TABLE = "actor"

# Indexes to drop/recreate on logging. Discovered from schema/indexes.sql at
# runtime, but we record the names here so we know which ones to look for.
LOGGING_INDEX_NAMES = (
    "logging_type_timestamp_idx",
    "logging_namespace_title_idx",
    "logging_page_idx",
    "logging_actor_idx",
    "logging_params_gin_idx",
)
INDEXES_SQL_PATH = (
    Path(__file__).resolve().parent / "schema" / "indexes.sql"
)

# Per-session performance tuning (loader opens its own connection).
SESSION_TUNING_SQL = (
    "SET LOCAL synchronous_commit = OFF",
    "SET LOCAL maintenance_work_mem = '2GB'",
)

log = logging.getLogger("load_logging_xml")


# ---------------------------------------------------------------------------
# log_params parsing
# ---------------------------------------------------------------------------

def _to_jsonable(obj: Any) -> Any:
    """Recursively coerce a phpserialize-decoded structure to JSON-safe types.

    phpserialize yields:
      * dicts keyed by either ints or bytes
      * lists of values
      * bytes (PHP strings)
      * ints / floats / bool / None

    Postgres jsonb requires:
      * dicts with str keys
      * everything else JSON-serializable
    """
    if isinstance(obj, dict):
        out: dict[str, Any] = {}
        for k, v in obj.items():
            if isinstance(k, bytes):
                # PHP strings: best-effort UTF-8, fall back to latin-1 to never raise.
                try:
                    sk = k.decode("utf-8")
                except UnicodeDecodeError:
                    sk = k.decode("latin-1")
            else:
                sk = str(k)
            out[sk] = _to_jsonable(v)
        return out
    if isinstance(obj, (list, tuple)):
        return [_to_jsonable(x) for x in obj]
    if isinstance(obj, bytes):
        try:
            return obj.decode("utf-8")
        except UnicodeDecodeError:
            return obj.decode("latin-1")
    if isinstance(obj, float) and not math.isfinite(obj):
        # JSON spec forbids Infinity/-Infinity/NaN; Postgres jsonb rejects them.
        # Preserve the information losslessly as a string sentinel.
        if math.isnan(obj):
            return "NaN"
        return "Infinity" if obj > 0 else "-Infinity"
    # int, finite float, bool, None, str — already jsonable.
    return obj


def parse_log_params(raw: Optional[str]) -> Optional[Any]:
    """Parse the MediaWiki log_params blob.

    Returns a JSON-serializable Python value, or None if `raw` is None/empty.

    Strategy: try JSON first (newer rows), then phpserialize (older rows),
    finally fall back to {"raw": raw} for the rare freeform/key=value style.
    """
    if raw is None:
        return None
    s = raw.strip()
    if not s:
        return None

    # 1. JSON — by far the most common in 2020+ rows.
    # Route through _to_jsonable too: Python's json.loads accepts the
    # non-standard tokens Infinity/-Infinity/NaN as floats; we'd then re-emit
    # them as Infinity to Postgres jsonb, which rejects them.
    try:
        return _to_jsonable(json.loads(s))
    except (json.JSONDecodeError, ValueError):
        pass

    # 2. PHP-serialized — common in pre-2018 rows.
    # phpserialize raises a few different exception types depending on the
    # malformation. Catch broadly; the freeform fallback below is a safe net.
    try:
        decoded = phpserialize.loads(s.encode("utf-8", errors="surrogateescape"))
        return _to_jsonable(decoded)
    except Exception:
        pass

    # 3. Freeform — preserve the original string for later inspection.
    return {"raw": raw}


# ---------------------------------------------------------------------------
# XML streaming
# ---------------------------------------------------------------------------
#
# We initially used `mwxml.Dump` for parsing, but on real enwiki data its
# User.from_element raises TypeError on `<contributor><id /></contributor>`
# (empty <id> element, which appears in the wild). Rather than monkey-patch
# mwxml, we roll a small iterparse-based parser. The schema is fixed and tiny
# (id, timestamp, contributor{username,id,ip}, comment, type, action,
# logtitle, params), so this stays small.

# MediaWiki export-0.11 namespace.
_MW_NS = "{http://www.mediawiki.org/xml/export-0.11/}"


@dataclass
class ParsedLogItem:
    id: Optional[int]
    type: Optional[str]
    action: Optional[str]
    timestamp: Optional[str]
    comment: Optional[str]
    comment_deleted: bool
    user_text: Optional[str]
    user_id: Optional[int]
    user_deleted: bool
    logtitle: Optional[str]
    params: Optional[str]


def open_xml_stream(path: Path) -> io.IOBase:
    """Return a binary file-like that ElementTree's iterparse can read."""
    if path.suffix == ".gz":
        return gzip.open(str(path), "rb")
    return open(path, "rb")


def _localname(tag: str) -> str:
    """Strip the {namespace} prefix from an ElementTree tag."""
    if tag.startswith("{"):
        return tag.rsplit("}", 1)[1]
    return tag


def _parse_namespaces(siteinfo_elem: ET.Element) -> dict[str, int]:
    """Build {prefix-lowercase: int_key} from <siteinfo>/<namespaces>.

    Used to split a logtitle like "User talk:Foo" into (3, "Foo"). We only
    look up by canonical/localized prefix; if the title doesn't match any
    known prefix we treat it as namespace 0 (Main).
    """
    ns_map: dict[str, int] = {}
    namespaces = siteinfo_elem.find(f"{_MW_NS}namespaces")
    if namespaces is None:
        return ns_map
    for n in namespaces.findall(f"{_MW_NS}namespace"):
        key = n.get("key")
        if key is None:
            continue
        try:
            key_int = int(key)
        except ValueError:
            continue
        prefix = (n.text or "").strip()
        if prefix:
            ns_map[prefix.lower()] = key_int
    return ns_map


def split_title(logtitle: str, ns_map: dict[str, int]) -> tuple[int, str]:
    """Decompose 'User talk:Foo' → (3, 'Foo'). Default to (0, full)."""
    if ":" in logtitle:
        prefix, _, rest = logtitle.partition(":")
        ns_id = ns_map.get(prefix.lower())
        if ns_id is not None:
            return ns_id, rest
    return 0, logtitle


def _text_or_none(elem: Optional[ET.Element]) -> Optional[str]:
    if elem is None:
        return None
    return elem.text  # may itself be None for <tag />


def _parse_contributor(c: ET.Element) -> tuple[
    Optional[str], Optional[int], bool
]:
    """Return (user_text, user_id, deleted)."""
    if c.get("deleted") is not None:
        return None, None, True
    username_e = c.find(f"{_MW_NS}username")
    ip_e = c.find(f"{_MW_NS}ip")
    id_e = c.find(f"{_MW_NS}id")
    user_text: Optional[str] = None
    user_id: Optional[int] = None
    if username_e is not None and username_e.text:
        user_text = username_e.text
    elif ip_e is not None and ip_e.text:
        user_text = ip_e.text
    if id_e is not None and id_e.text and id_e.text.strip():
        try:
            user_id = int(id_e.text)
        except ValueError:
            user_id = None
    return user_text, user_id, False


def iter_logitems(path: Path) -> Iterator[tuple[ParsedLogItem, dict[str, int]]]:
    """Yield (ParsedLogItem, ns_map) tuples.

    ns_map is built from <siteinfo> and reused across all items in the file.
    Yielded as a tuple so callers don't have to thread the namespace map
    out-of-band.

    Memory: ElementTree builds the tree as it parses. We clear each finished
    element *and* the root, so the <mediawiki> root never accumulates the
    ~50M emptied <logitem> shells — without root.clear() the process grows
    unboundedly and slows down badly over a multi-hour run.
    """
    f = open_xml_stream(path)
    ns_map: dict[str, int] = {}
    try:
        # 'start' events are used only to capture the root element; all real
        # work happens on 'end', when each child is fully populated.
        context = ET.iterparse(f, events=("start", "end"))
        _event, root = next(context)
        for event, elem in context:
            if event != "end":
                continue
            tag = _localname(elem.tag)
            if tag == "siteinfo":
                ns_map = _parse_namespaces(elem)
                elem.clear()
                root.clear()
                continue
            if tag != "logitem":
                # Children of <siteinfo>/<logitem> fire 'end' too; they are
                # freed when their parent is cleared below.
                continue

            # Parse this <logitem>.
            id_e = elem.find(f"{_MW_NS}id")
            ts_e = elem.find(f"{_MW_NS}timestamp")
            type_e = elem.find(f"{_MW_NS}type")
            action_e = elem.find(f"{_MW_NS}action")
            logtitle_e = elem.find(f"{_MW_NS}logtitle")
            params_e = elem.find(f"{_MW_NS}params")
            comment_e = elem.find(f"{_MW_NS}comment")
            contributor_e = elem.find(f"{_MW_NS}contributor")

            log_id: Optional[int] = None
            if id_e is not None and id_e.text and id_e.text.strip():
                try:
                    log_id = int(id_e.text)
                except ValueError:
                    log_id = None

            comment_deleted = False
            comment_text: Optional[str] = None
            if comment_e is not None:
                if comment_e.get("deleted") is not None:
                    comment_deleted = True
                else:
                    comment_text = comment_e.text

            user_text: Optional[str] = None
            user_id: Optional[int] = None
            user_deleted = False
            if contributor_e is not None:
                user_text, user_id, user_deleted = _parse_contributor(
                    contributor_e
                )

            item = ParsedLogItem(
                id=log_id,
                type=_text_or_none(type_e),
                action=_text_or_none(action_e),
                timestamp=_text_or_none(ts_e),
                comment=comment_text,
                comment_deleted=comment_deleted,
                user_text=user_text,
                user_id=user_id,
                user_deleted=user_deleted,
                logtitle=_text_or_none(logtitle_e),
                params=_text_or_none(params_e),
            )
            yield item, ns_map
            # Free memory: drop this logitem and any prior emptied shells.
            elem.clear()
            root.clear()
    finally:
        try:
            f.close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Actor synthesis
# ---------------------------------------------------------------------------

ACTOR_CACHE_MAX = 1_000_000


class ActorRegistry:
    """DB-backed actor resolver with a bounded LRU, resolving a whole batch
    of contributors per call.

    Key:    (actor_user_or_None, actor_name_bytes)
    Value:  actor_id (bigint allocated by the DB IDENTITY column)

    The schema declares ``actor_id GENERATED BY DEFAULT AS IDENTITY`` and
    ``UNIQUE NULLS NOT DISTINCT (actor_user, actor_name)``. Per-row resolution
    cost one network round-trip per cache miss, which dominated runtime once
    the working set outgrew the cache (~19M distinct actors in the log, mostly
    one-shot ``newusers`` performers). ``resolve_batch`` instead COPYs all the
    cache misses into a session TEMP table and runs two set-based statements:
    an ``INSERT ... SELECT ... ON CONFLICT DO NOTHING`` to mint ids, then a
    join back to read every id (minted or pre-existing) at once. The two
    loaders still converge on the same actor_id for the same key regardless
    of order.

    The LRU skips the COPY for contributors already seen in this process
    (admins recur constantly). Cap defaults to 1M entries.
    """

    _TEMP_DDL = (
        "CREATE TEMP TABLE IF NOT EXISTS _actor_keys "
        "(actor_user bigint, actor_name bytea) ON COMMIT PRESERVE ROWS"
    )
    _INSERT_SQL = (
        f"INSERT INTO {ACTOR_TABLE} (actor_user, actor_name) "
        "SELECT actor_user, actor_name FROM _actor_keys "
        "ON CONFLICT (actor_user, actor_name) DO NOTHING"
    )
    _JOIN_SQL = (
        "SELECT a.actor_id, k.actor_user, k.actor_name "
        f"FROM _actor_keys k JOIN {ACTOR_TABLE} a "
        "ON a.actor_user IS NOT DISTINCT FROM k.actor_user "
        "AND a.actor_name = k.actor_name"
    )

    def __init__(self, conn: psycopg.Connection, max_size: int = ACTOR_CACHE_MAX):
        self._conn = conn
        self._max_size = max_size
        # OrderedDict for cheap LRU semantics.
        from collections import OrderedDict
        self._cache: "OrderedDict[tuple[Optional[int], bytes], int]" = OrderedDict()

    def resolve_batch(
        self, keys: Iterable[tuple[Optional[int], bytes]]
    ) -> dict[tuple[Optional[int], bytes], int]:
        """Resolve many (actor_user, actor_name) keys to actor_ids at once.

        Returns a dict mapping every distinct input key to its actor_id. Cache
        hits are served from the LRU; misses — however many — are resolved
        with a single COPY plus two set-based statements.
        """
        result: dict[tuple[Optional[int], bytes], int] = {}
        misses: list[tuple[Optional[int], bytes]] = []
        miss_seen: set[tuple[Optional[int], bytes]] = set()
        for key in keys:
            cached = self._cache.get(key)
            if cached is not None:
                self._cache.move_to_end(key)
                result[key] = cached
            elif key not in miss_seen:
                miss_seen.add(key)
                misses.append(key)

        if misses:
            with self._conn.cursor() as cur:
                cur.execute(self._TEMP_DDL)
                cur.execute("TRUNCATE _actor_keys")
                with cur.copy(
                    "COPY _actor_keys (actor_user, actor_name) FROM STDIN"
                ) as cp:
                    for k in misses:
                        cp.write_row(k)
                cur.execute(self._INSERT_SQL)
                cur.execute(self._JOIN_SQL)
                for actor_id, actor_user, actor_name in cur.fetchall():
                    key = (actor_user, bytes(actor_name))
                    result[key] = actor_id
                    self._cache[key] = actor_id
                    self._cache.move_to_end(key)
            while len(self._cache) > self._max_size:
                self._cache.popitem(last=False)
            for k in misses:
                if k not in result:
                    raise RuntimeError(
                        f"actor key unresolved after batch insert: {k!r}"
                    )
        return result


# ---------------------------------------------------------------------------
# Index drop / recreate
# ---------------------------------------------------------------------------

def parse_logging_index_statements(indexes_sql: Path) -> dict[str, str]:
    """Parse schema/indexes.sql and return {index_name: full CREATE statement}
    for each logging-table index we know about."""
    text = indexes_sql.read_text(encoding="utf-8")
    statements: dict[str, str] = {}
    # Split on ';' at end of lines — each CREATE INDEX is one statement.
    # Handle multi-line statements (everything up to the next ';').
    raw_stmts = [s.strip() for s in text.split(";") if s.strip()]
    for stmt in raw_stmts:
        # Strip leading psql meta lines (\set, comments) defensively.
        # Match "CREATE INDEX [IF NOT EXISTS] name".
        m = re.search(
            r"CREATE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z0-9_]+)",
            stmt, flags=re.IGNORECASE,
        )
        if not m:
            continue
        name = m.group(1)
        if name in LOGGING_INDEX_NAMES:
            # Strip leading SQL comments so each statement re-runs cleanly.
            cleaned = re.sub(r"^\s*--[^\n]*\n", "", stmt, flags=re.MULTILINE)
            statements[name] = cleaned.strip() + ";"
    return statements


def drop_logging_indexes(conn: psycopg.Connection) -> dict[str, str]:
    """DROP every known logging index. Returns the saved CREATE statements.

    Idempotent: missing indexes are fine (DROP IF EXISTS).
    """
    creates = parse_logging_index_statements(INDEXES_SQL_PATH)
    missing = [n for n in LOGGING_INDEX_NAMES if n not in creates]
    if missing:
        log.warning(
            "indexes.sql parsed but these expected indexes were not found: %s",
            missing,
        )
    with conn.cursor() as cur:
        for name in LOGGING_INDEX_NAMES:
            log.info("dropping index %s", name)
            cur.execute(f"DROP INDEX IF EXISTS {name}")
    conn.commit()
    return creates


def recreate_logging_indexes(
    conn: psycopg.Connection, creates: dict[str, str]
) -> None:
    """Recreate the indexes we dropped, in the original order."""
    with conn.cursor() as cur:
        for name in LOGGING_INDEX_NAMES:
            stmt = creates.get(name)
            if not stmt:
                log.warning("no recreate statement for %s; skipping", name)
                continue
            log.info("recreating index %s", name)
            t0 = time.time()
            cur.execute(stmt)
            log.info("  -> %s built in %.1fs", name, time.time() - t0)
    conn.commit()


# ---------------------------------------------------------------------------
# Logging-table COPY
# ---------------------------------------------------------------------------

LOGGING_COLS = (
    "log_id",
    "log_type",
    "log_action",
    "log_timestamp",
    "log_actor",
    "log_actor_name",
    "log_namespace",
    "log_title",
    "log_page",
    "log_comment",
    "log_params",
    "log_deleted",
)

def _parse_ts(s: str) -> Optional[dt.datetime]:
    """Parse a MediaWiki ISO-8601 UTC timestamp ('2020-01-01T00:00:00Z')."""
    if not s:
        return None
    # Python's fromisoformat doesn't accept the trailing 'Z' until 3.11.
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        return dt.datetime.fromisoformat(s)
    except ValueError:
        return None


def _actor_key(
    item: ParsedLogItem,
) -> Optional[tuple[Optional[int], bytes]]:
    """Return the (actor_user, actor_name_bytes) key for this item's
    contributor, or None if the contributor is absent or revision-deleted."""
    if item.user_deleted or item.user_text is None:
        return None
    return (
        item.user_id,
        item.user_text.encode("utf-8", errors="surrogateescape"),
    )


def _logitem_to_row(
    item: ParsedLogItem,
    ns_map: dict[str, int],
    actor_map: dict[tuple[Optional[int], bytes], int],
) -> Optional[tuple]:
    """Map a ParsedLogItem to a row tuple matching LOGGING_COLS.

    Returns None if the item is unusable (no id, no type, no timestamp).
    The contributor's key must already be present in ``actor_map`` — the
    caller batch-resolves every contributor in the batch before calling this.
    """
    if item.id is None or item.type is None or item.timestamp is None:
        return None
    ts = _parse_ts(item.timestamp)
    if ts is None:
        return None

    # type/action are NOT NULL in our schema. action defaults to type if missing
    # (some old rows have no <action>).
    log_type = item.type
    log_action = item.action or item.type

    # logtitle: decompose with the dump's namespace map.
    if item.logtitle:
        log_namespace, title_str = split_title(item.logtitle, ns_map)
    else:
        log_namespace, title_str = 0, ""
    log_title_bytes = title_str.encode("utf-8", errors="surrogateescape")

    # contributor → actor. The key is resolved upstream in actor_map.
    actor_id: Optional[int]
    actor_name_bytes: Optional[bytes]
    key = _actor_key(item)
    if key is None:
        actor_id = None
        actor_name_bytes = None
    else:
        actor_name_bytes = key[1]
        actor_id = actor_map[key]

    log_comment = None if item.comment_deleted else item.comment

    # log_deleted: mirror MW's bitmask. The XML only flags comment/user for
    # log items (no text-suppression flag), so we set bits 2 and 4 only.
    log_deleted = 0
    if item.comment_deleted:
        log_deleted |= 2
    if item.user_deleted:
        log_deleted |= 4

    log_params = parse_log_params(item.params)
    log_params_json = (
        json.dumps(log_params, ensure_ascii=False)
        if log_params is not None else None
    )

    return (
        int(item.id),
        log_type,
        log_action,
        ts,
        actor_id,
        actor_name_bytes,
        int(log_namespace),
        log_title_bytes,
        None,  # log_page — not in pages-logging.xml
        log_comment,
        log_params_json,
        log_deleted,
    )


def _copy_logging_batch(
    conn: psycopg.Connection, rows: list[tuple]
) -> None:
    """Bulk-load a batch of logging rows via text-format COPY.

    We use the text format (not binary) because jsonb in binary COPY needs
    a hand-built leading version byte; text format lets psycopg/Postgres
    handle the encoding for every column type uniformly.
    """
    if not rows:
        return
    with conn.cursor() as cur:
        with cur.copy(
            f"COPY {LOGGING_TABLE} ({', '.join(LOGGING_COLS)}) FROM STDIN"
        ) as cp:
            for r in rows:
                cp.write_row(r)


# ---------------------------------------------------------------------------
# Main load
# ---------------------------------------------------------------------------

def load(
    file_path: Path,
    *,
    limit: Optional[int] = None,
    dry_run: bool = False,
    keep_indexes: bool = False,
    resume: bool = False,
) -> int:
    log.info("load: file=%s limit=%s dry_run=%s keep_indexes=%s resume=%s",
             file_path, limit, dry_run, keep_indexes, resume)
    if not file_path.exists():
        raise SystemExit(f"input file does not exist: {file_path}")

    type_hist: collections.Counter[str] = collections.Counter()
    seen = 0
    inserted = 0
    t0 = time.time()

    if dry_run:
        # Just iterate and count.
        for item, _ns_map in iter_logitems(file_path):
            seen += 1
            if item.type:
                type_hist[item.type] += 1
            if seen % PROGRESS_EVERY == 0:
                log.info("dry-run: parsed %d logitems in %.1fs",
                         seen, time.time() - t0)
            if limit and seen >= limit:
                break
        log.info("DRY-RUN summary: %d logitems parsed in %.1fs",
                 seen, time.time() - t0)
        log.info("type histogram: %s", type_hist.most_common(10))
        return seen

    # Real load. Open one connection; do everything in it.
    with psycopg.connect(f"service={SERVICE}") as conn:
        with conn.cursor() as cur:
            for stmt in SESSION_TUNING_SQL:
                cur.execute(stmt)

        actors = ActorRegistry(conn)

        # Resume mode: don't TRUNCATE; pick up after the last committed log_id.
        # MediaWiki's pages-logging dump emits <logitem> elements ordered by
        # log_id ascending, so we can skip any item with log_id <= max(log_id).
        min_log_id: Optional[int] = None
        if resume:
            with conn.cursor() as cur:
                cur.execute(f"SELECT COALESCE(MAX(log_id), 0) FROM {LOGGING_TABLE}")
                row = cur.fetchone()
                max_log_id = int(row[0]) if row else 0
            if max_log_id == 0:
                log.info("--resume: %s is empty; nothing to resume from", LOGGING_TABLE)
            else:
                min_log_id = max_log_id + 1
                log.info("--resume: skipping items with log_id <= %d", max_log_id)

        saved_index_creates: dict[str, str] = {}
        if not keep_indexes:
            saved_index_creates = drop_logging_indexes(conn)

        if not resume:
            # TRUNCATE logging only; never actor.
            with conn.cursor() as cur:
                log.info("TRUNCATE %s", LOGGING_TABLE)
                cur.execute(f"TRUNCATE TABLE {LOGGING_TABLE}")
            conn.commit()
        else:
            log.info("resume: skipping TRUNCATE; existing rows preserved")

        item_batch: list[tuple[ParsedLogItem, dict[str, int]]] = []
        skipped_resume = 0

        def flush_batch() -> int:
            """Batch-resolve every contributor, build rows, COPY, commit.

            Returns the number of rows actually inserted (items with no
            id/type/timestamp map to None and are dropped).
            """
            if not item_batch:
                return 0
            actor_map = actors.resolve_batch(
                k for k in (_actor_key(it) for it, _ in item_batch)
                if k is not None
            )
            rows = []
            for it, ns in item_batch:
                row = _logitem_to_row(it, ns, actor_map)
                if row is not None:
                    rows.append(row)
            _copy_logging_batch(conn, rows)
            conn.commit()
            item_batch.clear()
            return len(rows)

        try:
            for item, ns_map in iter_logitems(file_path):
                seen += 1
                if item.type:
                    type_hist[item.type] += 1
                if min_log_id is not None and item.id is not None and int(item.id) < min_log_id:
                    skipped_resume += 1
                    if skipped_resume % 1_000_000 == 0:
                        log.info("resume: fast-forwarded past %d items", skipped_resume)
                    continue
                item_batch.append((item, ns_map))

                if len(item_batch) >= BATCH_SIZE:
                    inserted += flush_batch()

                if seen % PROGRESS_EVERY == 0:
                    elapsed = time.time() - t0
                    rate = seen / elapsed if elapsed > 0 else 0.0
                    log.info(
                        "progress: %d parsed, %d inserted, %.0f rows/s, %.1fs",
                        seen, inserted, rate, elapsed,
                    )

                if limit and seen >= limit:
                    break

            # Flush remainder.
            inserted += flush_batch()
        except Exception:
            log.exception("load failed; rolling back current batch")
            conn.rollback()
            raise

        if not keep_indexes and saved_index_creates:
            recreate_logging_indexes(conn, saved_index_creates)

        with conn.cursor() as cur:
            log.info("ANALYZE %s, %s", LOGGING_TABLE, ACTOR_TABLE)
            cur.execute(f"ANALYZE {LOGGING_TABLE}")
            cur.execute(f"ANALYZE {ACTOR_TABLE}")
        conn.commit()

    elapsed = time.time() - t0
    log.info("DONE in %.1fs", elapsed)
    log.info("seen=%d inserted=%d", seen, inserted)
    log.info("top log_types: %s", type_hist.most_common(10))
    return inserted


# ---------------------------------------------------------------------------
# Self-test (no DB)
# ---------------------------------------------------------------------------

def self_test() -> int:
    """Exercise log_params parsing and a few edge cases. Returns exit code."""
    failures: list[str] = []

    # 1. JSON form (newer rows: nested array).
    json_raw = '[["edit=sysop"],{"7d": 0, "1y": 0}]'
    out = parse_log_params(json_raw)
    expected = [["edit=sysop"], {"7d": 0, "1y": 0}]
    if out != expected:
        failures.append(f"JSON parse: got {out!r}, want {expected!r}")

    # 2. JSON dict form (block log).
    json_dict = '{"5::duration": "indefinite", "6::flags": "nocreate"}'
    out = parse_log_params(json_dict)
    if out != {"5::duration": "indefinite", "6::flags": "nocreate"}:
        failures.append(f"JSON-dict parse: got {out!r}")

    # 3. PHP-serialized array (older rows).
    # PHP equiv: a:1:{i:0;s:10:"edit=sysop";}
    # phpserialize represents this as {0: b'edit=sysop'} — int keys preserved
    # rather than being collapsed to a list. We stringify the keys for jsonb.
    php_raw = 'a:1:{i:0;s:10:"edit=sysop";}'
    out = parse_log_params(php_raw)
    if out != {"0": "edit=sysop"}:
        failures.append(f"PHP parse simple: got {out!r}")

    # 4. PHP-serialized assoc array with bytes keys.
    # a:2:{s:5:"level";s:5:"sysop";s:6:"expiry";s:8:"infinity";}
    php_assoc = 'a:2:{s:5:"level";s:5:"sysop";s:6:"expiry";s:8:"infinity";}'
    out = parse_log_params(php_assoc)
    if out != {"level": "sysop", "expiry": "infinity"}:
        failures.append(f"PHP parse assoc: got {out!r}")

    # 5. Freeform / unparseable: stored as {"raw": ...}.
    free_raw = "edit=sysop\nmove=sysop"
    out = parse_log_params(free_raw)
    if out != {"raw": free_raw}:
        failures.append(f"freeform fallback: got {out!r}")

    # 6. None / empty.
    if parse_log_params(None) is not None:
        failures.append("None did not return None")
    if parse_log_params("") is not None:
        failures.append("empty string did not return None")
    if parse_log_params("   ") is not None:
        failures.append("blank string did not return None")

    # 7. JSON-encodability of every result.
    for raw in (json_raw, json_dict, php_raw, php_assoc, free_raw):
        try:
            json.dumps(parse_log_params(raw), ensure_ascii=False)
        except (TypeError, ValueError) as e:
            failures.append(f"non-JSON-encodable for {raw!r}: {e}")

    # 8. ActorRegistry.resolve_batch with a fake DB that emulates the TEMP
    # table + IDENTITY + ON CONFLICT semantics. The real DB hands out
    # monotonically-increasing ids and dedups via the unique constraint; we
    # mirror that in-memory.

    class _FakeCopy:
        def __init__(self, sink):
            self._sink = sink

        def __enter__(self):
            return self

        def __exit__(self, *a):
            return False

        def write_row(self, row):
            self._sink.append(tuple(row))

    class _FakeCur:
        """Cursor stub backed by a shared store: an `actor` map
        ((actor_user, actor_name) -> id) and an `_actor_keys` temp list."""

        def __init__(self, store):
            self._store = store
            self._rows: list[tuple] = []

        def __enter__(self):
            return self

        def __exit__(self, *a):
            return False

        def execute(self, sql: str, params=()):
            s = " ".join(sql.lower().split())
            if s.startswith("create temp table"):
                pass
            elif s.startswith("truncate"):
                self._store["tmp"].clear()
            elif s.startswith("insert into actor"):
                for au, an in self._store["tmp"]:
                    key = (au, an)
                    if key not in self._store["map"]:
                        self._store["map"][key] = self._store["next_id"]
                        self._store["next_id"] += 1
            elif s.startswith("select a.actor_id"):
                self._rows = [
                    (self._store["map"][(au, an)], au, an)
                    for au, an in self._store["tmp"]
                ]
            else:
                self._rows = []

        def copy(self, sql):
            return _FakeCopy(self._store["tmp"])

        def fetchall(self):
            return self._rows

    class _FakeConn:
        def __init__(self):
            self._store = {"map": {}, "next_id": 1, "tmp": []}

        def cursor(self):
            return _FakeCur(self._store)

    reg = ActorRegistry(_FakeConn())
    m = reg.resolve_batch([
        (123, b"Alice"), (123, b"Alice"),          # dedup within batch
        (None, b"127.0.0.1"), (None, b"127.0.0.1"),  # anonymous IP, dedup
    ])
    a = m[(123, b"Alice")]
    c = m[(None, b"127.0.0.1")]
    if a == c:
        failures.append("distinct keys collapsed to same actor_id")
    # Second batch: served from the LRU, must return the same ids.
    m2 = reg.resolve_batch([(123, b"Alice"), (None, b"127.0.0.1")])
    if m2[(123, b"Alice")] != a or m2[(None, b"127.0.0.1")] != c:
        failures.append(f"actor dedup across batches: {m2} vs a={a} c={c}")

    # 9. _logitem_to_row edge: deleted contributor + missing comment.
    item = ParsedLogItem(
        id=7, type="delete", action="delete",
        timestamp="2020-01-01T00:00:00Z",
        comment=None, comment_deleted=True,
        user_text=None, user_id=None, user_deleted=True,
        logtitle="User talk:Foo", params=None,
    )
    ns_map = {"user talk": 3}
    # Deleted contributor → key is None, so an empty actor_map suffices.
    row = _logitem_to_row(item, ns_map, {})
    if row is None:
        failures.append("deleted item produced None row")
    else:
        # log_actor (col 4) must be NULL
        if row[4] is not None:
            failures.append(f"deleted contributor not NULL: {row[4]!r}")
        # log_namespace decomposed correctly
        if row[6] != 3:
            failures.append(f"namespace decomposition: got {row[6]}")
        if row[7] != b"Foo":
            failures.append(f"title bytes: got {row[7]!r}")
        # log_comment (col 9) must be NULL
        if row[9] is not None:
            failures.append(f"deleted comment not NULL: {row[9]!r}")
        # log_deleted (col 11) bitmask = 6 (comment=2 | user=4)
        if row[11] != 6:
            failures.append(f"log_deleted bitmask: got {row[11]}, want 6")

    # 10. _logitem_to_row: missing log_page case + present contributor.
    item2 = ParsedLogItem(
        id=8, type="protect", action="protect",
        timestamp="2020-01-01T00:00:00Z",
        comment="x", comment_deleted=False,
        user_text="Alice", user_id=42, user_deleted=False,
        logtitle="Donald Trump",
        params='[["edit=sysop"],{"7d":0}]',
    )
    key2 = _actor_key(item2)
    row2 = _logitem_to_row(item2, {}, {key2: 4242})
    if row2 is None:
        failures.append("normal protect item produced None row")
    elif row2[8] is not None:
        failures.append(f"log_page should be NULL: got {row2[8]!r}")
    elif row2[4] != 4242:
        failures.append(f"log_actor should come from actor_map: got {row2[4]!r}")

    if failures:
        print("SELF-TEST FAILURES:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print("self-test: all checks passed")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--file", type=Path, default=DEFAULT_FILE,
                   help=f"path to pages-logging XML[.gz] (default: {DEFAULT_FILE})")
    p.add_argument("--limit", type=int, default=None,
                   help="stop after N logitems (testing)")
    p.add_argument("--dry-run", action="store_true",
                   help="parse and count, but do not load")
    p.add_argument("--keep-indexes", action="store_true",
                   help="don't drop/recreate indexes around the load")
    p.add_argument("--resume", action="store_true",
                   help="resume an interrupted load: skip TRUNCATE and fast-forward "
                        "past items with log_id <= MAX(log_id) already in the DB. "
                        "Relies on MediaWiki emitting <logitem> in log_id-ascending order.")
    p.add_argument("--self-test", action="store_true",
                   help="run in-script unit tests for log_params parsing and exit")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="enable DEBUG-level logging")
    args = p.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )

    if args.self_test:
        return self_test()

    load(
        args.file,
        limit=args.limit,
        dry_run=args.dry_run,
        keep_indexes=args.keep_indexes,
        resume=args.resume,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
