#!/usr/bin/env python3
"""
load_stub_history_xml.py — Phase 2 ingest of enwiki stub-meta-history XML
into the Postgres ``revision`` and ``actor`` tables of the wiki20260401 DB.

The 27 ``stub-meta-history*.xml.gz`` parts replace the retired
``revision.sql.gz`` dump. They contain every revision's metadata (no
wikitext): rev_id, page id, contributor, timestamp, minor flag, comment,
sha1, byte length, parent revision id. We synthesize the ``actor`` table
on the fly by deduplicating ``<contributor>`` blocks.

Loader strategy
---------------
1. Drop non-PK indexes on ``revision`` (PK kept — without it COPY would not
   fail loudly on a duplicate revision id, which would silently corrupt the
   downstream hyperevent dataset).
2. ``TRUNCATE revision`` (do NOT TRUNCATE actor: shared with logging loader).
3. For each input file: stream-parse with mwxml, batch revisions, COPY into
   ``revision``. Look up / insert each unique contributor in ``actor`` and
   cache the resulting actor_id in a per-process LRU.
4. After all files: re-create indexes and ANALYZE.

Actor identity (important — read before changing)
-------------------------------------------------
``schema/actor.sql`` declares ``actor_id GENERATED BY DEFAULT AS IDENTITY``
with ``UNIQUE NULLS NOT DISTINCT (actor_user, actor_name)``, so we never
allocate ids ourselves and the unique constraint covers both anon
(actor_user IS NULL) and registered editors. For each unseen contributor
we run ``INSERT ... ON CONFLICT (actor_user, actor_name) DO NOTHING
RETURNING actor_id``; if a sibling loader already inserted the row we
SELECT the id back. A bounded LRU caches resolved ids per process.

Edge cases handled
------------------
* Anon contributor (``<contributor><ip>1.2.3.4</ip></contributor>``):
  actor_user NULL, ip stored in actor_name as bytea.
* Deleted contributor (``<contributor deleted="deleted"/>``): rev_actor NULL.
  Schema's rev_actor is nullable, so we keep the revision row and NULL out
  rev_actor rather than dropping the row.
* Deleted comment, missing sha1, missing rev_len: NULL in revision.
* ``<minor/>`` self-closing: boolean true.

CLI
---
    python load_stub_history_xml.py
    python load_stub_history_xml.py --files <p1> <p2>
    python load_stub_history_xml.py --dry-run
    python load_stub_history_xml.py --limit N
    python load_stub_history_xml.py --workers N
    python load_stub_history_xml.py --keep-indexes

Connect via libpq ``service=wiki`` (port encoded in ~/.pg_service.conf).
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import gzip
import logging
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Iterator, Optional

import mwxml
import psycopg

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DUMP_XML_DIR = Path("/media/simone/ssd1/wikidumps/20260401/xml")
STUB_HISTORY_GLOB = "enwiki-20260401-stub-meta-history*.xml.gz"

PG_SERVICE = "service=wiki"
BATCH_SIZE = 50_000
PROGRESS_EVERY = 100_000

REVISION_INDEXES = {
    # name -> CREATE INDEX statement (matches schema/indexes.sql)
    "revision_page_timestamp_actor_idx": (
        "CREATE INDEX IF NOT EXISTS revision_page_timestamp_actor_idx "
        "ON revision (rev_page, rev_timestamp, rev_actor)"
    ),
    "revision_actor_timestamp_idx": (
        "CREATE INDEX IF NOT EXISTS revision_actor_timestamp_idx "
        "ON revision (rev_actor, rev_timestamp)"
    ),
    "revision_parent_idx": (
        "CREATE INDEX IF NOT EXISTS revision_parent_idx "
        "ON revision (rev_parent_id) WHERE rev_parent_id IS NOT NULL"
    ),
}

# Actor table: id allocation and dedup live entirely in the schema (IDENTITY
# column + UNIQUE NULLS NOT DISTINCT). The loader does not manage any actor
# DDL — it only INSERTs with ON CONFLICT.

logger = logging.getLogger("load_stub_history_xml")


# ---------------------------------------------------------------------------
# Tuple shape for COPY into revision
# ---------------------------------------------------------------------------

@dataclasses.dataclass(slots=True)
class RevisionRow:
    rev_id: int
    rev_page: int
    rev_actor: Optional[int]
    rev_timestamp: dt.datetime   # tz-aware UTC; binary COPY needs datetime
    rev_minor: bool
    rev_comment: Optional[str]
    rev_sha1: Optional[str]
    rev_len: Optional[int]
    rev_parent_id: Optional[int]


# ---------------------------------------------------------------------------
# Actor cache (per process)
# ---------------------------------------------------------------------------

class ActorResolver:
    """Resolve a (user_id, name) tuple to an actor_id. Cached, DB-backed.

    Cache key: (user_id_or_None, name_bytes). Cache value: actor_id (int).

    On cache miss: ``INSERT INTO actor (actor_user, actor_name) VALUES (%s, %s)
    ON CONFLICT (actor_user, actor_name) DO NOTHING RETURNING actor_id``. If
    RETURNING is empty (a sibling loader already inserted the row), SELECT the
    id back. The schema's IDENTITY column allocates actor_id; we never mint
    ids here. Cache is bounded by ``max_size`` with LRU eviction.
    """

    def __init__(self, conn: psycopg.Connection, max_size: int = 1_000_000):
        self.conn = conn
        self.max_size = max_size
        # Use OrderedDict for cheap LRU.
        from collections import OrderedDict
        self._cache: "OrderedDict[tuple[Optional[int], bytes], int]" = OrderedDict()
        # Pre-prepared statements
        self._sel = (
            "SELECT actor_id FROM actor "
            "WHERE actor_user IS NOT DISTINCT FROM %s AND actor_name = %s"
        )
        self._ins = (
            "INSERT INTO actor (actor_user, actor_name) VALUES (%s, %s) "
            "ON CONFLICT (actor_user, actor_name) DO NOTHING "
            "RETURNING actor_id"
        )

    def resolve(self, user_id: Optional[int], name: Optional[bytes]) -> Optional[int]:
        """Return actor_id, or None if both inputs are None / actor is suppressed.

        ``name`` must be bytes (the actor.actor_name column is bytea); pass
        ``None`` if the contributor was deleted.
        """
        if name is None:
            return None
        key = (user_id, name)
        cache = self._cache
        hit = cache.get(key)
        if hit is not None:
            cache.move_to_end(key)
            return hit
        with self.conn.cursor() as cur:
            cur.execute(self._ins, (user_id, name))
            row = cur.fetchone()
            if row is not None:
                actor_id = row[0]
            else:
                # Conflict — another writer beat us (or hit it before us).
                cur.execute(self._sel, (user_id, name))
                got = cur.fetchone()
                if got is None:
                    raise RuntimeError(
                        f"actor row vanished after ON CONFLICT for "
                        f"(actor_user={user_id!r}, actor_name={name!r})"
                    )
                actor_id = got[0]
        cache[key] = actor_id
        cache.move_to_end(key)
        if len(cache) > self.max_size:
            cache.popitem(last=False)
        return actor_id


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class ParseStats:
    revisions_seen: int = 0
    revisions_loaded: int = 0
    null_actor_deleted_user: int = 0   # contributor suppressed: rev_actor=NULL
    skipped_no_user: int = 0   # revision had no <contributor> at all (rare)


def _ts_to_datetime(ts) -> dt.datetime:
    """mwtypes.Timestamp -> tz-aware UTC datetime (for binary COPY)."""
    # mwtypes.Timestamp exposes a unix() integer; rebuild a UTC datetime.
    return dt.datetime.fromtimestamp(int(ts.unix()), tz=dt.timezone.utc)


def _name_to_bytes(name) -> Optional[bytes]:
    """Encode a contributor name (or IP) to bytes for actor.actor_name (bytea).

    Names from mwxml are str (the XML decoder has already done UTF-8). We
    re-encode as UTF-8; the actor table column is bytea (byte-transparent),
    matching MediaWiki's VARBINARY(255).
    """
    if name is None:
        return None
    if isinstance(name, bytes):
        return name
    return str(name).encode("utf-8", errors="surrogatepass")


def parse_file(
    path: Path,
    actor: ActorResolver,
    stats: ParseStats,
    limit: Optional[int] = None,
) -> Iterator[RevisionRow]:
    """Stream-parse one stub-meta-history file and yield RevisionRow objects.

    Resolves contributor -> actor_id inline via the supplied ActorResolver.
    """
    if path.suffix == ".gz":
        fp = gzip.open(path, "rt", encoding="utf-8", errors="surrogatepass")
    else:
        fp = open(path, "rt", encoding="utf-8", errors="surrogatepass")
    try:
        dump = mwxml.Dump.from_file(fp)
        for page in dump:
            page_id = page.id
            for rev in page:
                stats.revisions_seen += 1
                if limit is not None and stats.revisions_loaded >= limit:
                    return

                # Contributor handling.
                if rev.deleted and rev.deleted.user:
                    # <contributor deleted="deleted"/>: actor unknown but the
                    # revision is real. Schema's rev_actor is nullable, so we
                    # keep the row with rev_actor=NULL.
                    stats.null_actor_deleted_user += 1
                    actor_id: Optional[int] = None
                elif rev.user is None:
                    # Should not happen for stub dumps unless XML is unusual.
                    stats.skipped_no_user += 1
                    continue
                else:
                    user_id = rev.user.id  # may be None for anon
                    user_name = rev.user.text  # username or IP string
                    name_bytes = _name_to_bytes(user_name)
                    actor_id = actor.resolve(user_id, name_bytes)
                    if actor_id is None:
                        stats.skipped_no_user += 1
                        continue

                # Comment handling.
                if rev.deleted and rev.deleted.comment:
                    comment = None
                else:
                    comment = rev.comment

                # rev_len comes from <text bytes="N" /> (mwtypes exposes as .bytes)
                rev_len = rev.bytes  # already int or None

                # parent_id: cast to int when present.
                parent_id = int(rev.parent_id) if rev.parent_id is not None else None

                yield RevisionRow(
                    rev_id=int(rev.id),
                    rev_page=int(page_id),
                    rev_actor=actor_id,
                    rev_timestamp=_ts_to_datetime(rev.timestamp),
                    rev_minor=bool(rev.minor),
                    rev_comment=comment,
                    rev_sha1=rev.sha1,
                    rev_len=rev_len,
                    rev_parent_id=parent_id,
                )
                stats.revisions_loaded += 1
    finally:
        fp.close()


# ---------------------------------------------------------------------------
# COPY writer
# ---------------------------------------------------------------------------

COPY_COLUMNS = (
    "rev_id", "rev_page", "rev_actor", "rev_timestamp", "rev_minor",
    "rev_comment", "rev_sha1", "rev_len", "rev_parent_id",
)


def copy_batch(conn: psycopg.Connection, rows: list[RevisionRow]) -> None:
    """COPY a batch of RevisionRows into ``revision`` via psycopg's binary COPY."""
    if not rows:
        return
    cols = ", ".join(COPY_COLUMNS)
    sql = f"COPY revision ({cols}) FROM STDIN WITH (FORMAT BINARY)"
    with conn.cursor() as cur, cur.copy(sql) as cp:
        # Tell psycopg the column types so it serializes correctly.
        cp.set_types(
            ["int8", "int8", "int8", "timestamptz", "bool",
             "text", "text", "int8", "int8"]
        )
        for r in rows:
            cp.write_row((
                r.rev_id, r.rev_page, r.rev_actor, r.rev_timestamp,
                r.rev_minor, r.rev_comment, r.rev_sha1, r.rev_len,
                r.rev_parent_id,
            ))


# ---------------------------------------------------------------------------
# Per-file driver
# ---------------------------------------------------------------------------

def load_one_file(
    path: Path,
    limit: Optional[int],
    dry_run: bool,
) -> dict:
    """Load a single XML file. Returns a stats dict suitable for logging.

    Each invocation opens its own DB connection so this is safe to call from
    a worker process.
    """
    t0 = time.time()
    stats = ParseStats()

    if dry_run:
        # No DB connection; just iterate to count.
        # We still need an ActorResolver-shaped stub because parse_file calls
        # resolve() — but in dry-run we want a no-op that returns a fake id.
        class _FakeActor:
            def resolve(self, user_id, name):
                return 0 if name is not None else None
        for _row in parse_file(path, _FakeActor(), stats, limit=limit):
            n_loaded = stats.revisions_loaded
            if n_loaded and n_loaded % PROGRESS_EVERY == 0:
                logger.info(
                    "[%s] dry-run: %d revisions parsed",
                    path.name, stats.revisions_loaded,
                )
        elapsed = time.time() - t0
        logger.info(
            "[%s] dry-run done: seen=%d loaded=%d null_actor_deleted_user=%d "
            "skipped_no_user=%d in %.1fs",
            path.name, stats.revisions_seen, stats.revisions_loaded,
            stats.null_actor_deleted_user, stats.skipped_no_user, elapsed,
        )
        return {
            "file": path.name,
            "seen": stats.revisions_seen,
            "loaded": stats.revisions_loaded,
            "null_actor_deleted_user": stats.null_actor_deleted_user,
            "skipped_no_user": stats.skipped_no_user,
            "elapsed_sec": elapsed,
        }

    with psycopg.connect(PG_SERVICE) as conn:
        # Per-session perf knobs.
        with conn.cursor() as cur:
            cur.execute("SET LOCAL synchronous_commit = OFF")
            cur.execute("SET LOCAL maintenance_work_mem = '2GB'")
            cur.execute("SET LOCAL work_mem = '256MB'")
        actor = ActorResolver(conn)

        batch: list[RevisionRow] = []
        last_logged = 0
        for row in parse_file(path, actor, stats, limit=limit):
            batch.append(row)
            if len(batch) >= BATCH_SIZE:
                copy_batch(conn, batch)
                conn.commit()
                batch.clear()
            if stats.revisions_loaded - last_logged >= PROGRESS_EVERY:
                logger.info(
                    "[%s] %d revisions loaded (%.0f rev/s)",
                    path.name, stats.revisions_loaded,
                    stats.revisions_loaded / max(time.time() - t0, 1e-6),
                )
                last_logged = stats.revisions_loaded
        if batch:
            copy_batch(conn, batch)
            conn.commit()
            batch.clear()

    elapsed = time.time() - t0
    logger.info(
        "[%s] done: seen=%d loaded=%d null_actor_deleted_user=%d "
        "skipped_no_user=%d in %.1fs (%.0f rev/s)",
        path.name, stats.revisions_seen, stats.revisions_loaded,
        stats.null_actor_deleted_user, stats.skipped_no_user, elapsed,
        stats.revisions_loaded / max(elapsed, 1e-6),
    )
    return {
        "file": path.name,
        "seen": stats.revisions_seen,
        "loaded": stats.revisions_loaded,
        "null_actor_deleted_user": stats.null_actor_deleted_user,
        "skipped_no_user": stats.skipped_no_user,
        "elapsed_sec": elapsed,
    }


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------

def discover_files() -> list[Path]:
    files = sorted(DUMP_XML_DIR.glob(STUB_HISTORY_GLOB))
    return files


def _natural_part_key(p: Path):
    """Sort stub-meta-historyN by integer N, not lexicographically."""
    name = p.name
    # ...stub-meta-historyN.xml.gz  or  ...stub-meta-historyN-PARTIDS.xml.gz
    import re
    m = re.search(r"stub-meta-history(\d+)", name)
    return int(m.group(1)) if m else -1


def setup_indexes(conn: psycopg.Connection, drop: bool) -> None:
    """Optionally drop non-PK indexes on ``revision`` before bulk load.

    Actor table id allocation and dedup live in the schema (IDENTITY column +
    UNIQUE NULLS NOT DISTINCT); nothing here touches actor.
    """
    with conn.cursor() as cur:
        if drop:
            for idx in REVISION_INDEXES:
                logger.info("dropping index %s (will be re-created post-load)", idx)
                cur.execute(f"DROP INDEX IF EXISTS {idx}")
    conn.commit()


def recreate_indexes(conn: psycopg.Connection) -> None:
    """Re-create the dropped non-PK indexes on ``revision`` and ANALYZE."""
    with conn.cursor() as cur:
        cur.execute("SET maintenance_work_mem = '4GB'")
        for name, stmt in REVISION_INDEXES.items():
            t0 = time.time()
            logger.info("creating %s ...", name)
            cur.execute(stmt)
            logger.info("created %s in %.1fs", name, time.time() - t0)
        logger.info("ANALYZE revision ...")
        cur.execute("ANALYZE revision")
    conn.commit()


def truncate_revision(conn: psycopg.Connection) -> None:
    """TRUNCATE ``revision`` (do NOT touch actor — shared with other loaders)."""
    with conn.cursor() as cur:
        cur.execute("TRUNCATE TABLE revision")
        logger.info("TRUNCATEd revision")
    conn.commit()


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--files", nargs="+", default=None,
                   help="Specific stub-meta-history XML files to load.")
    p.add_argument("--dry-run", action="store_true",
                   help="Parse and count only; do not connect to the DB.")
    p.add_argument("--limit", type=int, default=None,
                   help="Limit total revisions loaded per file (testing).")
    p.add_argument("--workers", type=int, default=1,
                   help="Parallel processes loading files (default 1).")
    p.add_argument("--keep-indexes", action="store_true",
                   help="Do not drop / recreate non-PK indexes.")
    p.add_argument("--no-truncate", action="store_true",
                   help="Skip TRUNCATE revision (testing/incremental).")
    p.add_argument("--log-level", default="INFO",
                   help="Logging level (default INFO).")
    args = p.parse_args(argv)

    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    if args.files:
        files = [Path(f) for f in args.files]
    else:
        files = discover_files()
    if not files:
        logger.error("no input files matched %s/%s",
                     DUMP_XML_DIR, STUB_HISTORY_GLOB)
        return 2
    files = sorted(files, key=_natural_part_key)

    logger.info("plan: %d files, workers=%d dry_run=%s limit=%s keep_indexes=%s",
                len(files), args.workers, args.dry_run, args.limit,
                args.keep_indexes)
    for f in files:
        if not f.exists():
            logger.error("missing file: %s", f)
            return 2
        logger.info("  %s (%.1f MB)", f, f.stat().st_size / (1024 * 1024))

    if not args.dry_run:
        with psycopg.connect(PG_SERVICE) as conn:
            setup_indexes(conn, drop=not args.keep_indexes)
            if not args.no_truncate:
                truncate_revision(conn)

    t0 = time.time()
    results: list[dict] = []
    if args.workers > 1 and not args.dry_run:
        with ProcessPoolExecutor(max_workers=args.workers) as ex:
            futures = {
                ex.submit(load_one_file, f, args.limit, args.dry_run): f
                for f in files
            }
            for fut in as_completed(futures):
                results.append(fut.result())
    else:
        for f in files:
            results.append(load_one_file(f, args.limit, args.dry_run))

    if not args.dry_run and not args.keep_indexes:
        with psycopg.connect(PG_SERVICE) as conn:
            recreate_indexes(conn)

    total_loaded = sum(r["loaded"] for r in results)
    total_seen = sum(r["seen"] for r in results)
    total_skipped_du = sum(r["null_actor_deleted_user"] for r in results)
    total_skipped_nu = sum(r["skipped_no_user"] for r in results)
    elapsed = time.time() - t0
    logger.info("=" * 60)
    logger.info("ALL DONE in %.1fs: seen=%d loaded=%d null_actor_deleted_user=%d "
                "skipped_no_user=%d", elapsed, total_seen, total_loaded,
                total_skipped_du, total_skipped_nu)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
