-- Phase 2: synthesized during stub-meta-history and pages-logging XML loads.
-- The official actor.sql.gz dump is no longer published, so the loader builds
-- this table by deduplicating <contributor> blocks across both XML streams.
-- actor_name is bytea: usernames and IPv6 strings are stored as VARBINARY(255)
-- in MW and old rows have included non-UTF-8 bytes. actor_user is nullable —
-- anonymous edits carry only an IP (in actor_name) with no user_id.
--
-- actor_id is generated by the DB (IDENTITY) so loaders never have to allocate
-- ids themselves. The UNIQUE on (actor_user, actor_name) with NULLS NOT
-- DISTINCT is what makes ON CONFLICT-based upsert work for both registered
-- editors and anon (IP-only) editors: under NULLS NOT DISTINCT a NULL in
-- actor_user is treated as equal to another NULL, so two anon rows with the
-- same IP correctly collide. Requires Postgres 15+ (we run PG18).

DROP TABLE IF EXISTS actor CASCADE;

CREATE TABLE actor (
    actor_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user  bigint,           -- nullable (anon editors)
    actor_name  bytea NOT NULL,   -- username for registered, IP for anon
    CONSTRAINT actor_user_name_uniq UNIQUE NULLS NOT DISTINCT (actor_user, actor_name)
);
